### ISSUE TITLE
Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.

### ISSUE THREAD

**Issue by jj0hns0n** [jj0hns0n/geonode#37]
file = /Users/ortelius/projects/geonode-dev/geonode/scratch/misc/EPA Remaining EIS.csv
----------------------------------------
upload_csv_file: http://localhost:8000/datatables/api/upload
----------------------------------------
```
Internal Server Error: /datatables/api/upload
Traceback (most recent call last):
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/contrib/datatables/views.py", line 26, in datatable_upload_api
    dt, msg = process_csv_file(instance)
  File "/Users/ortelius/projects/geonode-dev/geonode/geonode/contrib/datatables/utils.py", line 63, in process_csv_file
    sql_table = sql.make_table(csv_table,table_name)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/csvkit/sql.py", line 87, in make_table
    sql_table.append_column(make_column(column, no_constraints))
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 632, in append_column
    column._set_parent_with_dispatch(self)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/sqlalchemy/sql/base.py", line 433, in _set_parent_with_dispatch
    self._set_parent(parent)
  File "/Users/ortelius/.virtualenvs/geonode/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1208, in _set_parent
    "Column must be constructed with a non-blank name or "
ArgumentError: Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.
```

**Comment by raprasad** [comment]
Some potential options for Short Term:
### 1. Allow table upload to fail

### 2. Via API, allow user to specify ```no_header_row``` (as it does now)
- Have GeoNode auto-add column names: "column01", "column02" naming
- Later, user can use GeoNode to make friendlier column labels

### 3. At UI side, allow user to indicate  'no header row'
- Have UI side, auto-add column names before sending file to GeoNode
- UI will always pass ```no_header_row``` as False -- UI ensures header row exists
